abstract class BaseEntity {
  String get id; // The ID from the API (or temporary local ID if creating)
  DateTime get createdAt;
  DateTime get updatedAt;
  DateTime? get deletedAt;

  // The UUID generated by the client for the current pending sync action
  String? get syncId;

  // A status flag to track synchronization
  // e.g., 0 = synced, 1 = pending_create, 2 = pending_update, 3 = pending_delete
  int get syncStatus;

  Map<String, dynamic> toMap();
}
