// Mocks generated by Mockito 5.4.6 from annotations
// in cinephileapp/test/features/movies/data/local/movie_local_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:cinephileapp/features/movies/data/local/catalog_meta/dao.dart'
    as _i13;
import 'package:cinephileapp/features/movies/data/local/catalog_meta/entity.dart'
    as _i7;
import 'package:cinephileapp/features/movies/data/local/catalog_page/dao.dart'
    as _i12;
import 'package:cinephileapp/features/movies/data/local/catalog_page/entity.dart'
    as _i6;
import 'package:cinephileapp/features/movies/data/local/genre/dao.dart' as _i11;
import 'package:cinephileapp/features/movies/data/local/genre/entity.dart'
    as _i5;
import 'package:cinephileapp/features/movies/data/local/movie/dao.dart' as _i8;
import 'package:cinephileapp/features/movies/data/local/movie/entity.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:sqflite/sqflite.dart' as _i2;
import 'package:uuid/uuid.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUuid_1 extends _i1.SmartFake implements _i3.Uuid {
  _FakeUuid_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieEntity_2 extends _i1.SmartFake implements _i4.MovieEntity {
  _FakeMovieEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieGenreEntity_3 extends _i1.SmartFake
    implements _i5.MovieGenreEntity {
  _FakeMovieGenreEntity_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieCatalogPageEntity_4 extends _i1.SmartFake
    implements _i6.MovieCatalogPageEntity {
  _FakeMovieCatalogPageEntity_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieCatalogMetaEntity_5 extends _i1.SmartFake
    implements _i7.MovieCatalogMetaEntity {
  _FakeMovieCatalogMetaEntity_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDao extends _i1.Mock implements _i8.MovieDao {
  MockMovieDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i2.Database get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeDatabase_0(this, Invocation.getter(#db)),
          )
          as _i2.Database);

  @override
  _i3.Uuid get uuid =>
      (super.noSuchMethod(
            Invocation.getter(#uuid),
            returnValue: _FakeUuid_1(this, Invocation.getter(#uuid)),
          )
          as _i3.Uuid);

  @override
  _i4.MovieEntity fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeMovieEntity_2(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i4.MovieEntity);

  @override
  _i10.Future<_i4.MovieEntity?> getByMovieId(int? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#getByMovieId, [movieId]),
            returnValue: _i10.Future<_i4.MovieEntity?>.value(),
          )
          as _i10.Future<_i4.MovieEntity?>);

  @override
  _i10.Future<void> insert(_i4.MovieEntity? item) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [item]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> update(_i4.MovieEntity? item) =>
      (super.noSuchMethod(
            Invocation.method(#update, [item]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> softDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDelete, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> hardDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDelete, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i4.MovieEntity>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i10.Future<List<_i4.MovieEntity>>.value(
              <_i4.MovieEntity>[],
            ),
          )
          as _i10.Future<List<_i4.MovieEntity>>);

  @override
  _i10.Future<List<_i4.MovieEntity>> getModifiedSince(DateTime? lastSyncTime) =>
      (super.noSuchMethod(
            Invocation.method(#getModifiedSince, [lastSyncTime]),
            returnValue: _i10.Future<List<_i4.MovieEntity>>.value(
              <_i4.MovieEntity>[],
            ),
          )
          as _i10.Future<List<_i4.MovieEntity>>);
}

/// A class which mocks [MovieGenreDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieGenreDao extends _i1.Mock implements _i11.MovieGenreDao {
  MockMovieGenreDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i2.Database get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeDatabase_0(this, Invocation.getter(#db)),
          )
          as _i2.Database);

  @override
  _i3.Uuid get uuid =>
      (super.noSuchMethod(
            Invocation.getter(#uuid),
            returnValue: _FakeUuid_1(this, Invocation.getter(#uuid)),
          )
          as _i3.Uuid);

  @override
  _i5.MovieGenreEntity fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeMovieGenreEntity_3(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i5.MovieGenreEntity);

  @override
  _i10.Future<void> replaceForMovie(int? movieId, List<int>? genreIds) =>
      (super.noSuchMethod(
            Invocation.method(#replaceForMovie, [movieId, genreIds]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> insert(_i5.MovieGenreEntity? item) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [item]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> update(_i5.MovieGenreEntity? item) =>
      (super.noSuchMethod(
            Invocation.method(#update, [item]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> softDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDelete, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> hardDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDelete, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i5.MovieGenreEntity>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i10.Future<List<_i5.MovieGenreEntity>>.value(
              <_i5.MovieGenreEntity>[],
            ),
          )
          as _i10.Future<List<_i5.MovieGenreEntity>>);

  @override
  _i10.Future<List<_i5.MovieGenreEntity>> getModifiedSince(
    DateTime? lastSyncTime,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getModifiedSince, [lastSyncTime]),
            returnValue: _i10.Future<List<_i5.MovieGenreEntity>>.value(
              <_i5.MovieGenreEntity>[],
            ),
          )
          as _i10.Future<List<_i5.MovieGenreEntity>>);
}

/// A class which mocks [MovieCatalogPageDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieCatalogPageDao extends _i1.Mock
    implements _i12.MovieCatalogPageDao {
  MockMovieCatalogPageDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i2.Database get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeDatabase_0(this, Invocation.getter(#db)),
          )
          as _i2.Database);

  @override
  _i3.Uuid get uuid =>
      (super.noSuchMethod(
            Invocation.getter(#uuid),
            returnValue: _FakeUuid_1(this, Invocation.getter(#uuid)),
          )
          as _i3.Uuid);

  @override
  _i6.MovieCatalogPageEntity fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeMovieCatalogPageEntity_4(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i6.MovieCatalogPageEntity);

  @override
  _i10.Future<void> replacePage({
    required String? catalogKind,
    required int? page,
    required List<int>? orderedMovieIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replacePage, [], {
              #catalogKind: catalogKind,
              #page: page,
              #orderedMovieIds: orderedMovieIds,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i6.MovieCatalogPageEntity>> listSlots({
    required String? catalogKind,
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listSlots, [], {
              #catalogKind: catalogKind,
              #page: page,
            }),
            returnValue: _i10.Future<List<_i6.MovieCatalogPageEntity>>.value(
              <_i6.MovieCatalogPageEntity>[],
            ),
          )
          as _i10.Future<List<_i6.MovieCatalogPageEntity>>);

  @override
  _i10.Future<void> insert(_i6.MovieCatalogPageEntity? item) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [item]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> update(_i6.MovieCatalogPageEntity? item) =>
      (super.noSuchMethod(
            Invocation.method(#update, [item]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> softDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDelete, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> hardDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDelete, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i6.MovieCatalogPageEntity>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i10.Future<List<_i6.MovieCatalogPageEntity>>.value(
              <_i6.MovieCatalogPageEntity>[],
            ),
          )
          as _i10.Future<List<_i6.MovieCatalogPageEntity>>);

  @override
  _i10.Future<List<_i6.MovieCatalogPageEntity>> getModifiedSince(
    DateTime? lastSyncTime,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getModifiedSince, [lastSyncTime]),
            returnValue: _i10.Future<List<_i6.MovieCatalogPageEntity>>.value(
              <_i6.MovieCatalogPageEntity>[],
            ),
          )
          as _i10.Future<List<_i6.MovieCatalogPageEntity>>);
}

/// A class which mocks [MovieCatalogMetaDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieCatalogMetaDao extends _i1.Mock
    implements _i13.MovieCatalogMetaDao {
  MockMovieCatalogMetaDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i2.Database get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeDatabase_0(this, Invocation.getter(#db)),
          )
          as _i2.Database);

  @override
  _i3.Uuid get uuid =>
      (super.noSuchMethod(
            Invocation.getter(#uuid),
            returnValue: _FakeUuid_1(this, Invocation.getter(#uuid)),
          )
          as _i3.Uuid);

  @override
  _i7.MovieCatalogMetaEntity fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeMovieCatalogMetaEntity_5(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i7.MovieCatalogMetaEntity);

  @override
  _i10.Future<void> upsert(_i7.MovieCatalogMetaEntity? meta) =>
      (super.noSuchMethod(
            Invocation.method(#upsert, [meta]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i7.MovieCatalogMetaEntity?> get({
    required String? catalogKind,
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#get, [], {
              #catalogKind: catalogKind,
              #page: page,
            }),
            returnValue: _i10.Future<_i7.MovieCatalogMetaEntity?>.value(),
          )
          as _i10.Future<_i7.MovieCatalogMetaEntity?>);

  @override
  _i10.Future<void> insert(_i7.MovieCatalogMetaEntity? item) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [item]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> update(_i7.MovieCatalogMetaEntity? item) =>
      (super.noSuchMethod(
            Invocation.method(#update, [item]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> softDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDelete, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> hardDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDelete, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i7.MovieCatalogMetaEntity>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i10.Future<List<_i7.MovieCatalogMetaEntity>>.value(
              <_i7.MovieCatalogMetaEntity>[],
            ),
          )
          as _i10.Future<List<_i7.MovieCatalogMetaEntity>>);

  @override
  _i10.Future<List<_i7.MovieCatalogMetaEntity>> getModifiedSince(
    DateTime? lastSyncTime,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getModifiedSince, [lastSyncTime]),
            returnValue: _i10.Future<List<_i7.MovieCatalogMetaEntity>>.value(
              <_i7.MovieCatalogMetaEntity>[],
            ),
          )
          as _i10.Future<List<_i7.MovieCatalogMetaEntity>>);
}
