// Mocks generated by Mockito 5.4.6 from annotations
// in cinephileapp/test/features/movies/data/repositories/movie_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cinephileapp/core/data/json_dto.dart' as _i1;
import 'package:cinephileapp/core/data/paged_dto.dart' as _i3;
import 'package:cinephileapp/features/movies/data/dto/movie_dto.dart' as _i8;
import 'package:cinephileapp/features/movies/data/local/data_source.dart'
    as _i4;
import 'package:cinephileapp/features/movies/data/remote/data_source.dart'
    as _i9;
import 'package:cinephileapp/features/movies/domain/movie_catalog_kind.dart'
    as _i7;
import 'package:cinephileapp/features/movies/domain/paged_movies.dart' as _i6;
import 'package:mockito/mockito.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePagedDto_0<T extends _i1.JsonDto> extends _i2.SmartFake
    implements _i3.PagedDto<T> {
  _FakePagedDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i2.Mock
    implements _i4.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.PagedMovies?> getCatalogPage(
    _i7.MovieCatalogKind? kind,
    int? page,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCatalogPage, [kind, page]),
            returnValue: _i5.Future<_i6.PagedMovies?>.value(),
          )
          as _i5.Future<_i6.PagedMovies?>);

  @override
  _i5.Future<void> saveCatalogPage(
    _i7.MovieCatalogKind? kind,
    _i3.PagedDto<_i8.MovieDto>? remotePage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveCatalogPage, [kind, remotePage]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i2.Mock
    implements _i9.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.PagedDto<_i8.MovieDto>> fetchCatalog(
    _i7.MovieCatalogKind? kind, {
    int? page = 1,
    String? language,
    String? region,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchCatalog,
              [kind],
              {#page: page, #language: language, #region: region},
            ),
            returnValue: _i5.Future<_i3.PagedDto<_i8.MovieDto>>.value(
              _FakePagedDto_0<_i8.MovieDto>(
                this,
                Invocation.method(
                  #fetchCatalog,
                  [kind],
                  {#page: page, #language: language, #region: region},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.PagedDto<_i8.MovieDto>>);
}
